version: "3.8"

services:
  cpp:
    image: ntuangiang/opencv-mongo-cpp # Image latest
    environment:
      - DISPLAY=192.168.100.100:0
      - XAUTHORITY=/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority
    ports:
      - "2201:22" # Remote
      - "7776:7777" # Debug
    #   Linux: Enable 2 lines below.
    #    extra_hosts:
    #      host.docker.internal: "192.168.0.110"
    restart: always